"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  english: {
    agriNode: "AgriNode",
    tagline: "Turn your agri-waste into opportunity.",
    welcome: "Welcome to AgriNode",
    description:
      "List your surplus, connect with nearby buyers, and give agricultural waste a second life.",
    continueAsFarmer: "Continue as Farmer",
    continueAsBuyer: "Continue as Buyer",
    languageLabel: "Choose language",
    languageHelper: "Select your preferred language",
    dashboard: "Dashboard",
    myListings: "My Listings",
    messages: "Messages",
    impact: "Impact",
    farmer: "Farmer",
    buyer: "Buyer",
    guest: "Guest",
    login: "Login",
    logout: "Logout",
    agriWasteMarketplace: "Agri Waste Marketplace",
    farmerView: "Farmer view",
    agriNodeDashboard: "AgriNode dashboard",
    marketPitch: "Connect regional surplus to buyer demand.",
    listings: "Listings",
    yourActiveWasteOffers: "Your active waste offers",
    total: "total",
    loadingListings: "Loading listings from Firestore...",
    noListings: "No listings yet. Add your first agri-waste offer to begin the demo.",
    addListing: "Add listing",
    createNewOffer: "Create a new agri-waste offer",
    farmerName: "Farmer name",
    farmerNamePlaceholder: "Farmer or co-op name",
    wasteCategory: "Waste category",
    customWasteCategory: "Custom waste category",
    customWasteCategoryPlaceholder: "e.g. Rice husk, sawdust, palm frond",
    quantityTonnes: "Quantity (tonnes)",
    moisturePercent: "Moisture %",
    farmLocation: "Farm location",
    useMyLocation: "Use my location",
    placePinOnIndiaMap: "Place pin on India map",
    hideIndiaMap: "Hide India map",
    latitude: "Latitude",
    longitude: "Longitude",
    whatHappensNext: "What happens next",
    nextStep1: "Your listing is published to the cluster feed.",
    nextStep2: "Buyers in nearby regions can review your offer.",
    nextStep3: "You can accept a selected purchase through the escrow flow.",
    saving: "Saving...",
    addListingButton: "Add listing",
    buyerView: "Buyer view",
    regionalWasteDemand: "Regional waste demand",
    buyerPitch:
      "Clustered by similar produce within a ~10 km radius. Map shows cluster points only; farmer details appear after selection.",
    clusters: "Clusters",
    availableLots: "Available lots",
    allWaste: "All waste",
    paddy: "Paddy",
    bagasse: "Bagasse",
    banana: "Banana",
    sortBy: "Sort by",
    quantity: "Quantity",
    urgency: "Urgency",
    distance: "Distance",
    clusterView: "Cluster view",
    farmerMapView: "Farmer view",
    clusterSummary: "Cluster summary",
    selectCluster: "Select a cluster to view the live summary.",
    totalTonnes: "total",
    farmers: "farmers",
    avgMoisture: "avg moisture",
    contributingFarmers: "Contributing farmers",
    selectAll: "Select all",
    clearAll: "Clear all",
    chooseFarmer: "Choose at least one farmer or select the full cluster.",
    escrowLocked: "Escrow Locked",
    lockSelectedFarmers: "Lock selected",
    farmerSingular: "farmer",
    farmerPlural: "farmers",
    selectClusterDetail: "Select a cluster to view its details.",
    clusterLabel: "Cluster",
    totalTonnesValue: "Total tonnes",
    farmersValue: "Farmers",
    confirmEscrow: "Confirm escrow",
    demoEscrowNote: "Demo escrow only — no real payment will be processed.",
    cancel: "Cancel",
    confirmWholeCluster: "Confirm whole cluster",
    confirmSelection: "Confirm selection",
    loadingWorkspace: "Loading your workspace",
    loadingWorkspaceCopy: "Checking your secure marketplace access…",
    pleaseSignIn: "Please sign in",
    pleaseSignInCopy: "You need an active account to access this marketplace.",
    goToLogin: "Go to login",
    accessRedirected: "Access redirected",
    pageReservedFor: "This page is reserved for the",
    workspace: "workspace.",
    returnTo: "Return to",
    welcomeBack: "Welcome back",
    createAccount: "Create account",
    signUpToAgriNode: "Sign up to AgriNode",
    loginToAgriNode: "Login to AgriNode",
    iAmA: "I am a",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    pleaseWait: "Please wait...",
    createAccountButton: "Create account",
    loginButton: "Login",
    logIn: "Log in",
    signUp: "Sign up",
    alreadyHaveAccount: "Already have an account?",
    needAnAccount: "Need an account?",
    roleRequired: "Please select a role.",
    emailPasswordRequired: "Email and password are required.",
    enterFullName: "Please enter your full name.",
    passwordsDoNotMatch: "Passwords do not match.",
    useStrongerPassword: "Use a stronger password with at least 6 characters.",
    enterValidEmail: "Enter a valid email address.",
    incorrectCredentials: "Incorrect email or password.",
    networkError: "Network error. Please try again.",
    authFailed: "Authentication failed. Please try again.",
    accountExists: "An account already exists for this email.",
    firebaseNotConfigured: "Firebase is not configured. Add your project credentials in .env.local.",
    chooseLanguage: "Choose language",
    languageOptions: ["English", "हिन्दी", "മലയാളം"],
    regMarketplace: "Regenerative marketplace",
    fieldNetworks: "Field networks · Circular sourcing",
    languageLabel: "Choose language",
  },
  hindi: {
    agriNode: "एग्रीनोड",
    tagline: "अपने कृषि-कचरे को अवसर में बदलें।",
    welcome: "एग्रीनोड में आपका स्वागत है",
    description:
      "अपना अतिरिक्त सामान सूचीबद्ध करें, पास के खरीदारों से जुड़ें, और कृषि-कचरे को दूसरी जिंदगी दें।",
    continueAsFarmer: "फार्मर के रूप में जारी रखें",
    continueAsBuyer: "खरीदार के रूप में जारी रखें",
    languageLabel: "भाषा चुनें",
    languageHelper: "अपनी पसंदीदा भाषा चुनें",
    dashboard: "डैशबोर्ड",
    myListings: "मेरी लिस्टिंग",
    messages: "संदेश",
    impact: "प्रभाव",
    farmer: "फार्मर",
    buyer: "खरीदार",
    guest: "अतिथि",
    login: "लॉगिन",
    logout: "लॉगआउट",
    agriWasteMarketplace: "कृषि अपशिष्ट मार्केटप्लेस",
    farmerView: "फार्मर व्यू",
    agriNodeDashboard: "एग्रीनोड डैशबोर्ड",
    marketPitch: "क्षेत्रीय अधिशेष को खरीदार मांग से जोड़ें।",
    listings: "लिस्टिंग",
    yourActiveWasteOffers: "आपकी सक्रिय अपशिष्ट ऑफर",
    total: "कुल",
    loadingListings: "Firestore से लिस्टिंग लोड हो रही है...",
    noListings: "अभी कोई लिस्टिंग नहीं है। अपनी पहली कृषि-अपशिष्ट ऑफर जोड़ें।",
    addListing: "लिस्टिंग जोड़ें",
    createNewOffer: "नई कृषि-अपशिष्ट ऑफर बनाएं",
    farmerName: "फार्मर का नाम",
    farmerNamePlaceholder: "फार्मर या सहकारिता का नाम",
    wasteCategory: "अपशिष्ट श्रेणी",
    customWasteCategory: "कस्टम अपशिष्ट श्रेणी",
    customWasteCategoryPlaceholder: "जैसे: चावल की भूसी, लकड़ी का बुरादा, ताड़ की पत्ती",
    quantityTonnes: "मात्रा (टन)",
    moisturePercent: "नमी %",
    farmLocation: "खेत का स्थान",
    useMyLocation: "मेरा स्थान उपयोग करें",
    placePinOnIndiaMap: "भारत के नक़्शे पर पिन रखें",
    hideIndiaMap: "भारत का नक्शा छिपाएँ",
    latitude: "अक्षांश",
    longitude: "देशांतर",
    whatHappensNext: "अगला कदम",
    nextStep1: "आपकी लिस्टिंग क्लस्टर फीड में प्रकाशित हो जाती है।",
    nextStep2: "पास के क्षेत्रों के खरीदार आपकी ऑफर देख सकते हैं।",
    nextStep3: "आप चयनित खरीद को escrow फ्लो के माध्यम से स्वीकार कर सकते हैं।",
    saving: "सहेजा जा रहा है...",
    addListingButton: "लिस्टिंग जोड़ें",
    buyerView: "खरीदार व्यू",
    regionalWasteDemand: "क्षेत्रीय अपशिष्ट मांग",
    buyerPitch:
      "~10 किमी के भीतर समान उत्पादों के आधार पर समूहित। मानचित्र केवल क्लस्टर बिंदु दिखाता है; चयन के बाद किसान का विवरण दिखाई देता है।",
    clusters: "क्लस्टर",
    availableLots: "उपलब्ध लॉट",
    allWaste: "सभी अपशिष्ट",
    paddy: "धान",
    bagasse: "गन्ने की पीठ",
    banana: "केला",
    sortBy: "क्रम sort",
    quantity: "मात्रा",
    urgency: "तत्कालता",
    distance: "दूरी",
    clusterView: "क्लस्टर व्यू",
    farmerMapView: "फार्मर व्यू",
    clusterSummary: "क्लस्टर सारांश",
    selectCluster: "लाइव सारांश देखने के लिए क्लस्टर चुनें।",
    totalTonnes: "कुल",
    farmers: "फार्मर",
    avgMoisture: "औसत नमी",
    contributingFarmers: "योगदान देने वाले फार्मर",
    selectAll: "सभी चुनें",
    clearAll: "सभी साफ़ करें",
    chooseFarmer: "कम से कम एक फार्मर चुनें या पूरा क्लस्टर चुनें।",
    escrowLocked: "एस्क्रो लॉक",
    lockSelectedFarmers: "चयनित लॉक करें",
    farmerSingular: "फार्मर",
    farmerPlural: "फार्मर",
    selectClusterDetail: "क्लस्टर के विवरण देखने के लिए चुनें।",
    clusterLabel: "क्लस्टर",
    totalTonnesValue: "कुल टन",
    farmersValue: "फार्मर",
    confirmEscrow: "एस्क्रो की पुष्टि करें",
    demoEscrowNote: "केवल डेमो एस्क्रो — कोई वास्तविक भुगतान नहीं किया जाएगा।",
    cancel: "रद्द करें",
    confirmWholeCluster: "पूरा क्लस्टर कन्फर्म करें",
    confirmSelection: "चयन की पुष्टि करें",
    loadingWorkspace: "आपका वर्कस्पेस लोड हो रहा है",
    loadingWorkspaceCopy: "आपकी सुरक्षित मार्केटप्लेस एक्सेस जांची जा रही है…",
    pleaseSignIn: "कृपया साइन इन करें",
    pleaseSignInCopy: "इस मार्केटप्लेस तक पहुँचने के लिए सक्रिय खाता आवश्यक है।",
    goToLogin: "लॉगिन पर जाएँ",
    accessRedirected: "एक्सेस रीडायरेक्टेड",
    pageReservedFor: "यह पेज",
    workspace: "वर्कस्पेस के लिए आरक्षित है।",
    returnTo: "पर लौटें",
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "अकाउंट बनाएं",
    signUpToAgriNode: "एग्रीनोड में साइन अप करें",
    loginToAgriNode: "एग्रीनोड में लॉगिन करें",
    iAmA: "मैं एक",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    pleaseWait: "कृपया प्रतीक्षा करें...",
    createAccountButton: "अकाउंट बनाएं",
    loginButton: "लॉगिन",
    logIn: "लॉग इन",
    signUp: "साइन अप",
    alreadyHaveAccount: "क्या आपके पास पहले से खाता है?",
    needAnAccount: "खाता चाहिए?",
    roleRequired: "कृपया भूमिका चुनें।",
    emailPasswordRequired: "ईमेल और पासवर्ड आवश्यक हैं।",
    enterFullName: "कृपया पूरा नाम दर्ज करें।",
    passwordsDoNotMatch: "पासवर्ड मैच नहीं कर रहे हैं।",
    useStrongerPassword: "कम से कम 6 वर्णों का मजबूत पासवर्ड चुनें।",
    enterValidEmail: "मान्य ईमेल दर्ज करें।",
    incorrectCredentials: "ईमेल या पासवर्ड गलत है।",
    networkError: "नेटवर्क त्रुटि। कृपया फिर से प्रयास करें।",
    authFailed: "प्रमाणीकरण विफल हुआ। कृपया पुनः प्रयास करें।",
    accountExists: "इस ईमेल के लिए पहले से खाता मौजूद है।",
    firebaseNotConfigured: "Firebase कॉन्फ़िगर नहीं है। .env.local में परियोजना क्रेडेंशियल जोड़ें।",
    chooseLanguage: "भाषा चुनें",
    languageOptions: ["English", "हिन्दी", "മലയാളം"],
    regMarketplace: "पुनर्योजी मार्केटप्लेस",
    fieldNetworks: "फील्ड नेटवर्क · सर्कुलर सोर्सिंग",
  },
  malayalam: {
    agriNode: "അഗ്രിനോഡ്",
    tagline: "നിങ്ങളുടെ കാർഷിക അവശിഷ്ടങ്ങളെ അവസരമാക്കി മാറ്റുക.",
    welcome: "അഗ്രിനോഡിലേക്ക് സ്വാഗതം",
    description:
      "നിങ്ങളുടെ അധിക ഉൽപ്പന്നങ്ങൾ ലിസ്റ്റുചെയ്യുക, സമീപത്തുള്ള വാങ്ങുന്നവരുമായി ബന്ധപ്പെടുക, കാർഷിക അവശിഷ്ടങ്ങൾക്ക് രണ്ടാം ജീവനായി നൽകുക.",
    continueAsFarmer: "കർഷകനായി തുടരുക",
    continueAsBuyer: "വാങ്ങിക്കാരനായി തുടരുക",
    languageLabel: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    languageHelper: "നിങ്ങളുടെ പ്രിയപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക",
    dashboard: "ഡാഷ്ബോർഡ്",
    myListings: "എന്റെ ലിസ്റ്റുകൾ",
    messages: "സന്ദേശങ്ങൾ",
    impact: "ഇംപാക്റ്റ്",
    farmer: "കർഷകൻ",
    buyer: "വാങ്ങിക്കാർ",
    guest: "അതിഥി",
    login: "ലോഗിൻ",
    logout: "ലോഗൗട്ട്",
    agriWasteMarketplace: "കാർഷിക മാലിന്യ മാർക്കറ്റ്‌പ്ലേസ്",
    farmerView: "കർഷക ദൃശ്യം",
    agriNodeDashboard: "അഗ്രിനോഡ് ഡാഷ്ബോർഡ്",
    marketPitch: "പ്രാദേശിക surplus-നെ വാങ്ങുന്നവരുടെ ആവശ്യവുമായി ബന്ധിപ്പിക്കുക.",
    listings: "ലിസ്റ്റുകൾ",
    yourActiveWasteOffers: "നിങ്ങളുടെ സജീവ വസ്തു ഓഫറുകൾ",
    total: "മൊത്തം",
    loadingListings: "Firestore-യിൽ നിന്ന് ലിസ്റ്റുകൾ లోഡിംഗ്...",
    noListings: "ഇതുവരെ ലിസ്റ്റുകളില്ല. ആദ്യമായി ഒരു കാർഷിക മാലിന്യ ഓഫർ ചേർക്കുക.",
    addListing: "ലിസ്റ്റ് ചേർക്കുക",
    createNewOffer: "പുതിയ കാർഷിക മാലിന്യ ഓഫർ സൃഷ്ടിക്കുക",
    farmerName: "കർഷകന്റെ പേര്",
    farmerNamePlaceholder: "കർഷകൻ അല്ലെങ്കിൽ കോ-ഓപ്പ് പേര്",
    wasteCategory: "മാലിന്യ വിഭാഗം",
    customWasteCategory: "കസ്റ്റം മാലിന്യ വിഭാഗം",
    customWasteCategoryPlaceholder: "ഉദാ: റൈസ് ഹസ്ക്, സാവ്ദസ്, പാം ഫ്രണ്ട്",
    quantityTonnes: "അളവ് (ടൺ)",
    moisturePercent: "തെളിച്ചം %",
    farmLocation: "കൃഷിയിടം",
    useMyLocation: "എന്റെ സ്ഥലമുപയോഗിക്കുക",
    placePinOnIndiaMap: "ഇന്ത്യാ മാപ്പിൽ പിന് വെക്കുക",
    hideIndiaMap: "ഇന്ത്യ മാപ്പ് മറയ്ക്കുക",
    latitude: "അക്ഷാംശം",
    longitude: "രേഖാംശം",
    whatHappensNext: "അടുത്തത് എന്ത്",
    nextStep1: "നിങ്ങളുടെ ലിസ്റ്റ് ക്ലസ്റ്റർ ഫീഡിൽ പ്രസിദ്ധീകരിക്കും.",
    nextStep2: "അടുത്ത പ്രദേശത്തെ വാങ്ങിക്കാർക്ക് നിങ്ങളുടെ ഓഫർ കാണാം.",
    nextStep3: "തിരഞ്ഞെടുത്ത വാങ്ങൽ escrows-ൽ സ്വീകരിക്കാം.",
    saving: "സേവ് ചെയ്യുന്നു...",
    addListingButton: "ലിസ്റ്റ് ചേർക്കുക",
    buyerView: "വാങ്ങിക്കാരൻ ദൃശ്യം",
    regionalWasteDemand: "പ്രദേശിക മാലിന്യ ആവശ്യം",
    buyerPitch:
      "~10 കിലോമീറ്റർ റേഡിയസിലുള്ള സമാന ഉൽപന്നങ്ങൾക്കനുസരിച്ചു ക്ലസ്റ്റർ ചെയ്യുന്നു. മാപ്പിൽ കേവലം ക്ലസ്റ്റർ പോയിൻ്റുകൾ മാത്രം കാണിക്കുന്നു; തരത്തിൽ തിരഞ്ഞെടുക്കുമ്പോൾ കർഷക വിശദാംശങ്ങൾ തുറക്കുന്നു.",
    clusters: "ക്ലസ്റ്ററുകൾ",
    availableLots: "ലഭ്യമായ ലോട്ടുകൾ",
    allWaste: "എല്ലാ മാലിന്യവും",
    paddy: "പാഡ്ഡി",
    bagasse: "ബഗാസെ",
    banana: "താഴമേൽ",
    sortBy: "ഇങ്ങനെ അടുക്കുക",
    quantity: "അളവ്",
    urgency: "അടിപാട്",
    distance: "ദൂരം",
    clusterView: "ക്ലസ്റ്റർ ദൃശ്യം",
    farmerMapView: "കർഷക ദൃശ്യം",
    clusterSummary: "ക്ലസ്റ്റർ സംഗ്രഹം",
    selectCluster: "라이വ് സംഗ്രഹം കാണാൻ ഒരു ക്ലസ്റ്റർ തിരഞ്ഞെടുക്കുക.",
    totalTonnes: "മൊത്തം",
    farmers: "കർഷകർ",
    avgMoisture: "ശരാശരി ഈർപ്പം",
    contributingFarmers: "സംഭാവന ചെയ്യുന്ന കർഷകർ",
    selectAll: "എല്ലാം തിരഞ്ഞെടുക്കുക",
    clearAll: "എല്ലാം മായ്ക്കുക",
    chooseFarmer: "കുറഞ്ഞത് ഒരു കർഷകനെ അല്ലെങ്കിൽ മുഴുവൻ ക്ലസ്റ്റർ തിരഞ്ഞെടുക്കുക.",
    escrowLocked: "എസ്ക്രോ ലോക്ക് ചെയ്തു",
    lockSelectedFarmers: "തിരഞ്ഞെടുത്തത് ലോക്ക് ചെയ്യുക",
    farmerSingular: "കർഷകൻ",
    farmerPlural: "കർഷകർ",
    selectClusterDetail: "ക്ലസ്റ്ററിന്റെ വിശദാംശങ്ങൾ കാണാൻ തിരഞ്ഞെടുക്കുക.",
    clusterLabel: "ക്ലസ്റ്റർ",
    totalTonnesValue: "മൊത്തം ടൺ",
    farmersValue: "കർഷകർ",
    confirmEscrow: "എസ്ക്രോ സ്ഥിരീകരിക്കുക",
    demoEscrowNote: "ഡെമോ escrows മാത്രം — യഥാർത്ഥ പണമൊന്നും കൈവശമില്ല.",
    cancel: "റദ്ദാക്കുക",
    confirmWholeCluster: "മുഴുവൻ ക്ലസ്റ്റർ സ്ഥിരീകരിക്കുക",
    confirmSelection: "തിരഞ്ഞെടുപ്പ് സ്ഥിരീകരിക്കുക",
    loadingWorkspace: "നിങ്ങളുടെ വർക്ക്സ്പേസ് ലോഡ് ചെയ്യുന്നു",
    loadingWorkspaceCopy: "നിങ്ങളുടെ സുരക്ഷിത മാർക്കറ്റ്‌പ്ലേസ് ആക്സസ് പരിശോധിക്കുന്നു…",
    pleaseSignIn: "ദയവായി സൈൻ ഇൻ ചെയ്യുക",
    pleaseSignInCopy: "ഈ മാർക്കറ്റ്‌പ്ലേസ് ആക്സസ് ചെയ്യാൻ സജീവ അക്കൗണ്ട് ആവശ്യമാണ്.",
    goToLogin: "ലോഗിൻ എന്നതിലേക്ക് പോകുക",
    accessRedirected: "ആക്സസ് റീഡയറക്ട് ചെയ്തു",
    pageReservedFor: "ഈ പേജ്",
    workspace: "വർക്ക്സ്പെയ്സിനായി റിസർവുചെയ്യപ്പെട്ടതാണ്.",
    returnTo: "ഇതിലേക്ക് തിരികെ പോകുക",
    welcomeBack: "വീണ്ടും欢迎",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    signUpToAgriNode: "അഗ്രിനോഡിൽ സൈൻ അപ്പ് ചെയ്യുക",
    loginToAgriNode: "അഗ്രിനോഡിൽ ലോഗിൻ ചെയ്യുക",
    iAmA: "ഞാൻ ഒരു",
    fullName: "പൂർണ്ണനാമം",
    email: "ഇമെയിൽ",
    password: "പാസ്സ്‌വേഡ്",
    confirmPassword: "പാസ്സ്‌വേഡ് സ്ഥിരീകരിക്കുക",
    pleaseWait: "ദയവായി കാത്തിരിക്കുക...",
    createAccountButton: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    loginButton: "ലോഗിൻ",
    logIn: "ലോഗിൻ",
    signUp: "സൈൻ അപ്പ്",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    needAnAccount: "അക്കൗണ്ട് വേണോ?",
    roleRequired: "ദയവായി ഒരു റോളും തിരഞ്ഞെടുക്കുക.",
    emailPasswordRequired: "ഇമെയിലും പാസ്‌വേഡ് ആവശ്യമാണ്.",
    enterFullName: "ദയവായി പൂർണ്ണനാമം നൽകുക.",
    passwordsDoNotMatch: "പാസ്സ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല.",
    useStrongerPassword: "കുറഞ്ഞത് 6 അക്ഷരമുളള ശക്തമായ പാസ്‌വേഡ് ഉപയോഗിക്കുക.",
    enterValidEmail: "സാധുവായ ഇമെയിൽ നൽകുക.",
    incorrectCredentials: "ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ് തെറ്റാണ്.",
    networkError: "നെറ്റ്‌വർക്ക് പിശക്. വീണ്ടും ശ്രമിക്കുക.",
    authFailed: "ആ throttling not?",
    accountExists: "ഈ ഇമെയിലിനായി അക്കൗണ്ട് ഇതിനകം ഉണ്ടാണ്.",
    firebaseNotConfigured: "Firebase കോൺഫിഗർ ചെയ്തിട്ടില്ല. .env.local-ൽ പ്രോജക്റ്റ് ക്രെഡൻഷ്യലുകൾ ചേർക്കുക.",
    chooseLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    languageOptions: ["English", "हिन्दी", "മലയാളം"],
    regMarketplace: "പുനരുപയോഗ മാര്ക്കറ്റ്",
    fieldNetworks: "ഫീൽഡ് नेटवर्कുകൾ · സർക്കുലാർ സോഴ്സിംഗ്",
  },
};

const languageOptions = [
  { value: "english", label: "English" },
  { value: "hindi", label: "हिन्दी" },
  { value: "malayalam", label: "മലയാളം" },
];

const LanguageContext = createContext({
  language: "english",
  setLanguage: () => {},
  t: translations.english,
  languages: languageOptions,
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("english");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("agri-language");
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
    localStorage.setItem("agri-language", language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language] || translations.english,
      languages: languageOptions,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
